# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.cache/wt [current_project]
set_property parent.project_path C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/alu/alu.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/exmemory/button.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/controller/controller.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/datapath/datapath.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/datapath/misc/dff.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/exmemory/display.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/exmemory/exmemory.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/datapath/misc/leftshift2.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/mips.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/datapath/misc/mux2.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/datapath/misc/mux4.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/datapath/pc.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/exmemory/ram.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/datapath/regfile.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/exmemory/rom.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/mips/datapath/misc/signextend.v
  C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/sources_1/imports/new/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/constrs_1/new/ports.xdc
set_property used_in_implementation false [get_files C:/Users/MUIMI/Desktop/LXProgectTest/new_slots/new_slots.srcs/constrs_1/new/ports.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
